# Propiedades de Markdown

> Bloque con sangría

## Texto resaltado (negrita)

probando la **negrita....**  ¿Anduvo?

## Itálica

se puede escribir también en *itálica* poniendo un solo asterisco


## Listas desordenadas

- casa
- perro 
- auto.

## Listas ordenadas

1. casa
2. perro 
3. auto
5. gato
10. pepe
1. Hola

## Enlaces (links) 

[GITHUB del Centro de Graduados FIUBA](https://github.com/Backpropagation-Limitada)

## Imágenes

![BELÉN](belen.jpg "A Belén le gustan los gatitos")

## Citas

> "El único usuario bueno es el usuario muerto"
>
> [Ángel "JAVA" López] (https://github.com/ajlopez)

---
___

## Tablas

|tables|are |cool| 
|----|:----:|----:|
|col 3 is|right-alined|1600| 
|col 2 is |centered|12|
|zebras are|neat|1|

## Operadores y resolución de expresiones

In [1]:
4 + 5

9

In [2]:
type(4.0+5) 

float

In [3]:
"Hola" + ' Mundo!!'

'Hola Mundo!!'

## Variables

In [4]:
type("Hola" + ' Mundo!!')

str

In [5]:
10 - 2

8

In [6]:
5 * 3 

15

In [7]:
type(5 * 3.0 )

float

In [8]:
"Hola" * 3

'HolaHolaHola'

In [9]:
10/2

5.0

In [10]:
type(10/2)

float

In [11]:
9/2

4.5

In [12]:
9//2

4

In [13]:
type(9//2) # parte entera

int

In [14]:
9%2

1

## Comentarios en Python

In [22]:
# Comentar una línea
# a=100

In [24]:
# Comentar atrás de una línea de código
a=100 # defino una variable

In [26]:
"""
a=1
a=1
a=1
a=1
a=1
a=1
"""
print("Hola")



Hola


In [17]:
# Creamos una variable de nombre x y le damos un valor
x=5.0

In [21]:
print("La variable x vale: " + str(x))

La variable x vale:5.0


In [24]:
print("La variable x vale:" , x)

La variable x vale: 5.0


In [18]:
# mostramos la variable
x

5.0

In [25]:
# Mostramos el tipo de la variable
type(x)

float

In [26]:
# Mostramos el valor verdad de la variable
bool(x)

True

In [27]:
bool(0)

False

In [29]:
bool(-55)

True

##### Desafío:
cambiar el valor 5 por 5.0, "cinco", True, False,0,1, (0), (), [], [0], {}, {0},  lo que se te ocurra, y repetí todos los pasos (mostrar, type, bool, ...)

In [31]:
y=8

In [32]:
Y

NameError: name 'Y' is not defined

In [33]:
print(y)

8


In [34]:
(x,y)=1,2

In [37]:
type((x,y))

tuple

In [0]:
x,y

(1, 2)

In [0]:
x,y=1,2,3

ValueError: too many values to unpack (expected 2)

In [47]:
a = 5
b = 10
print ("El valor de a es: " + str(a)+" El valor de b es: "+str(b))

El valor de a es: 5 El valor de b es: 10


In [48]:
a,b=b,a

In [49]:
print ("El valor de a es: " + str(a)+" El valor de b es: "+str(b))

El valor de a es: 10 El valor de b es: 5


# Tarea

Crear una variable de nombre ¨x¨ y con valor 10. Ejecutar. 


Mostrar el valor de la variable.

¿De qué otra forma se puede obtener el mismo resultado?

10

10


Crear 4 variables: a,b,c y d, con valores 10, 20, 30, and 40, respectivamente.

In [0]:
(a,b,c,d)=

Mostrar  el valor de b

10 20


Hacer lo mismo para d.

In [0]:
aux=a
a=b
b=aux
print(a,b)

20 10


5 10


In [0]:
# FUMATA DE SERGIO.....
if z==None:
    print ("No hay una variable definida llamada z")

NameError: name 'z' is not defined

In [0]:
try:
    if (z):
        print ("Hay una variable definida llamada z")
except (NameError):
        print ("No hay una variable definida llamada z")

No hay una variable definida llamada z


In [27]:
import numpy as np

In [29]:
a=np.array([[1,2,3],[4,5,6]])

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [33]:
a.shape

(2, 3)

In [35]:
a.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [37]:
(4 + 10) * 2 

28

In [38]:
4 + 5

9

In [39]:
_ * 2

18

In [1]:
_

''

In [2]:
4 ** 2

16

In [4]:
5 ** 4

625

In [5]:
type (1==2)

bool

In [6]:
4 == 2+2

True

In [8]:
4 < 2

False

In [9]:
10 == 5 *2 and 4 == 2 * 2 

True

In [12]:
1 or 0 

1

In [16]:
False ^ False

False

In [52]:
a = [[1,3],[4,6]]

In [53]:
a

[[1, 3], [4, 6]]